name: spark-ai-gems
description: ''
version: 0.1.9
author: maciej@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: spark_ai_gems
  parentArtefactID: prophecy_io
  buildSystem: wheel
  author: null
  createdAt: '2023-10-11 01:11:45'
pipelines:
  pipelines/BedrockTest:
    name: BedrockTest
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-11 03:18:47'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/SageMakerEndpointTest:
    name: SageMakerEndpointTest
    description: ''
    author: maciej@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-10-11 03:28:04'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems:
    gems/Bedrock:
      name: Bedrock
      category: Machine Learning
      subCategory: ''
      description: null
      author: maciej@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/Bedrock.py
      dependencies: null
      createdAt: '2023-10-11 01:12:21'
    gems/SageMakerEndpoint:
      name: SageMakerEndpoint
      category: Machine Learning
      subCategory: ''
      description: null
      author: maciej@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/SageMakerEndpoint.py
      dependencies: null
      createdAt: '2023-10-11 01:14:11'
    gems/OpenAI:
      name: OpenAI
      category: Machine Learning
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/OpenAI.py
      dependencies: null
      createdAt: '2023-12-06 06:36:58'
    gems/OpenSearchLookup:
      name: OpenSearchLookup
      category: Machine Learning
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/OpensearchLookup.py
      dependencies: null
      createdAt: '2023-12-06 06:42:31'
    gems/binary:
      name: binary
      category: Source/Target
      subCategory: File
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/Binary.py
      dependencies: null
      createdAt: '2023-12-06 06:43:14'
    gems/pinecone:
      name: pinecone
      category: Source/Target
      subCategory: Warehouse
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/Pinecone.py
      dependencies: null
      createdAt: '2023-12-06 06:44:45'
    gems/TextProcessing:
      name: TextProcessing
      category: Machine Learning
      subCategory: null
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/TextProcessing.py
      dependencies: null
      createdAt: '2023-12-06 06:46:22'
    gems/OpenSearch:
      name: OpenSearch
      category: Source/Target
      subCategory: Warehouse
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/Opensearch.py
      dependencies: null
      createdAt: '2023-12-06 07:07:45'
    gems/PineconeLookup:
      name: PineconeLookup
      category: Machine Learning
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/PineconeLookup.py
      dependencies: null
      createdAt: '2023-12-06 07:09:37'
    gems/Watermark:
      name: Watermark
      category: Transform
      subCategory: ''
      description: null
      author: sumitpaul@prophecy.io
      mode: batch
      files:
      - prophecy_io_spark_ai_gems/gems/Watermark.py
      dependencies: null
      createdAt: '2023-12-06 07:10:41'
  dependencies: null
functions:
  author: null
  createdAt: '2023-10-11 01:11:45'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.0.4
    isDefault: true
    author: null
    createdAt: '2023-10-11 01:11:45'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.2
    isDefault: true
    author: null
    createdAt: '2023-10-11 01:11:45'
pipelineConfigurations: {}
